apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer-pod
  name: multicontainer-pod
spec:
  containers:
  - image: httpd
    name: httpd
  - image: alpine
    name: debug
    command:
      - "sleep"
      - "999999999"
