apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-command
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sleep
            image: alpine
            command:
               - echo
               - "Buried Alive - Avenged Sevenfold"
          restartPolicy: "OnFailure"
