apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-retain
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-retain
